; Generated by scripts/vendor.sh — do not edit; edit the source named here.
; Source: packages/editors/tree-sitter-mx/queries/highlights.scm (MX's own grammar, decision 146 shorthands).

; Basic syntax highlighting for Marko templates.

; Statement-tag names are not tags visually: static/server/client are
; Marko keywords (the compiler strips them before parsing the body as TS),
; while import/export/class are part of the injected TS statement itself
; and take their color from that injection (see injections.scm).
((tag_name (tag_name_fragment) @tag)
 (#not-any-of? @tag "import" "export" "class" "static" "server" "client"))
((tag_name (tag_name_fragment) @keyword)
 (#any-of? @keyword "static" "server" "client"))
(close_tag_name) @tag
(shorthand_id) @constant
(shorthand_class) @property
; Every name-sugar form, tag-adjacent and in attribute position (decision 146).
(shorthand_name) @label

; MX (decision 156): an atom value, wherever an expression holds one. The
; injections leave atoms out of the TypeScript ranges (they are children of the
; expression node), so this capture is the only one on them. `::name` is
; reserved and has no capture.
(atom) @string.special.symbol

(attr_name) @attribute
; `=` and `:=` between a name and its value. The value itself is injected TS
; (injections.scm), so it takes no flat color.
(attr_eq) @operator
(attr_bound_eq) @operator
(attr_value_expr) @none

; Binding positions: patterns get the TS injection; types are captured
; flatly because a bare type is not a valid TS program (matching the
; tmLanguage grammar's source.ts#type approximation).
(var_pattern) @variable
(var_type) @type
(param_pattern) @variable.parameter
(param_type) @type
(param_default) @none
(type_expr) @type

(open_tag_start) @punctuation.bracket
(open_tag_end) @punctuation.bracket
(open_tag_end_self) @punctuation.bracket
(close_tag_start) @punctuation.bracket
(close_tag_end) @punctuation.bracket

(args_open) @punctuation.bracket
(args_close) @punctuation.bracket
(params_open) @punctuation.bracket
(params_close) @punctuation.bracket
(type_open) @punctuation.bracket
(type_close) @punctuation.bracket
(attr_group_open) @punctuation.bracket
(attr_group_close) @punctuation.bracket
(method_body_open) @punctuation.bracket
(method_body_close) @punctuation.bracket
(scriptlet_block_open) @punctuation.bracket
(scriptlet_block_close) @punctuation.bracket

(placeholder_start) @punctuation.special
(placeholder_start_raw) @punctuation.special
(placeholder_end) @punctuation.special

(html_comment) @comment
(line_comment) @comment
(block_comment) @comment

(doctype) @keyword
(declaration) @keyword
(cdata) @string

(scriptlet_start) @punctuation.special
(scriptlet_start_concise) @punctuation.special

(text) @none
