/**
 * `mx-angular build` (design note A3): compiles every routed `.mx` file to
 * its Angular output, applying the `onError` policy and writing only when
 * bytes differ.
 *
 * `compileOne()` is the single per-file compile path (round 1 R-a): both
 * `build()` here and `watch.ts`'s full/incremental rebuilds call it, so the
 * `onError` 3x2 table, the overwrite guard, the symlink guards, the header
 * and the map write exist in exactly one place.
 */

import {
  existsSync,
  lstatSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join } from "node:path";
import { getCustomTags, type MxWarning, TranslateError } from "@mxlang/core";
import { type AngularConfig, readAngularConfig } from "./config.ts";
import { discoverFiles, isInside } from "./discover.ts";
import { buildHeader, hasGeneratedHeader } from "./header.ts";
import { compileFile } from "./index.ts";
import { buildMap, writeMap } from "./map-file.ts";
import { compileTagModuleFile } from "./tag-module.ts";

/**
 * Refuses to write over an output that already exists and was not
 * generated by this tool (A3: "the emitted `.ts` must not collide with a
 * hand-written one" — applied to every output kind, not only tag modules,
 * so a hand-written page template is never clobbered either). Returns an
 * error message, or `undefined` if writing is safe.
 */
export function checkOverwriteGuard(outputPath: string): string | undefined {
  if (!existsSync(outputPath)) return undefined;
  const existing = readFileSync(outputPath, "utf8");
  if (hasGeneratedHeader(existing)) return undefined;
  return `refusing to overwrite \`${outputPath}\`, which MX did not generate; rename the tag file or the existing module.`;
}

export interface PositionedMessage {
  file: string;
  /** Absent for a failure with no source position (a thrown non-`TranslateError`). */
  line?: number;
  column?: number;
  message: string;
}

export interface BuildResult {
  ok: boolean;
  errors: PositionedMessage[];
  warnings: PositionedMessage[];
}

export function outputPathFor(mxPath: string, extension: string): string {
  const base = basename(mxPath, ".mx");
  return join(dirname(mxPath), `${base}${extension}`);
}

/**
 * Whether `path` is a symlink. `writeFileSync`/`unlinkSync` both follow a
 * symlink to its target by default; every output path here is derived from
 * a discovered `.mx` file's own directory, so a symlinked output slot would
 * let a compile silently write (or delete) outside the project tree it was
 * pointed at.
 */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

/** Writes `path` only when its bytes differ from what's on disk, and records it in `knownOutputs` (round 1 R-b) either way — even an unchanged write is this tool's own output, so a watcher must never treat its mtime-refreshing fs event as a foreign change. */
function writeIfDiffers(
  path: string,
  content: string,
  knownOutputs?: Set<string>,
): void {
  knownOutputs?.add(path);
  if (isSymlink(path)) {
    throw new Error(`refusing to write through a symlink: ${path}`);
  }
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (existing === content) return;
  }
  writeFileSync(path, content, "utf8");
}

/** The visible `<pre>` error template written on a cold start (A3's `onError` table). Always carries the generated header, so a later fix is never blocked by the overwrite guard (round 1 finding: an unheadered error template bricks the page forever). */
function errorTemplate(headerPrefix: string, message: string): string {
  const escaped = message
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `${headerPrefix}<!-- mx-angular: compile error -->\n<pre style="white-space:pre-wrap;color:#b00">${escaped}</pre>\n`;
}

/**
 * Applies the `onError` policy for a failed compile. Returns an overwrite-
 * guard error message when the policy would have written or deleted a
 * hand-written file — every branch (`delete`'s `unlinkSync`, `error-
 * template`'s and `keep-last`'s cold-start `writeIfDiffers`) checks
 * `checkOverwriteGuard` first, so a compile error never clobbers a file MX
 * did not generate; that would otherwise be a wrong error message ("this
 * is now broken because your template has an error") on someone else's
 * file, on every one of the three modes.
 */
function applyOnError(
  outputPath: string,
  headerPrefix: string,
  message: string,
  onError: AngularConfig["onError"],
  knownOutputs: Set<string>,
): { error?: string; line: string } {
  const hadPrevious = existsSync(outputPath);
  const generatedByUs = hadPrevious
    ? hasGeneratedHeader(readFileSync(outputPath, "utf8"))
    : false;

  if (onError === "delete") {
    if (hadPrevious) {
      if (!generatedByUs) {
        const err = checkOverwriteGuard(outputPath);
        return { error: err, line: `${outputPath} error: ${err}` };
      }
      if (isSymlink(outputPath)) {
        throw new Error(`refusing to delete through a symlink: ${outputPath}`);
      }
      unlinkSync(outputPath);
      knownOutputs.delete(outputPath);
      return { line: `${outputPath} skipped (deleted on error)` };
    }
    return {
      line: `${outputPath} skipped (no previous output; onError=delete)`,
    };
  }

  if (onError === "error-template") {
    if (hadPrevious && !generatedByUs) {
      const err = checkOverwriteGuard(outputPath);
      return { error: err, line: `${outputPath} error: ${err}` };
    }
    writeIfDiffers(
      outputPath,
      errorTemplate(headerPrefix, message),
      knownOutputs,
    );
    return { line: `${outputPath} wrote (error template)` };
  }

  // keep-last (default): leave a previous good output; write the error
  // template only on a cold start (no previous output at all), or when the
  // existing file is neither ours nor a good previous output — but never
  // over a file MX did not generate.
  if (!hadPrevious) {
    writeIfDiffers(
      outputPath,
      errorTemplate(headerPrefix, message),
      knownOutputs,
    );
    return { line: `${outputPath} wrote (error template, cold start)` };
  }
  if (!generatedByUs) {
    const err = checkOverwriteGuard(outputPath);
    return { error: err, line: `${outputPath} error: ${err}` };
  }
  return { line: `${outputPath} skipped (keeping last good output)` };
}

function warningsFor(file: string, warnings: MxWarning[]): PositionedMessage[] {
  return warnings.map((w) => ({
    file,
    line: w.line,
    column: w.column,
    message: w.message,
  }));
}

export interface CompileOneResult {
  ok: boolean;
  /** One line per write/skip/error, in `file:line:col message` shape where positioned. */
  lines: string[];
  errors: PositionedMessage[];
  warnings: PositionedMessage[];
  /**
   * Tag names this page called and the IR retained, for dependency tracking.
   * Empty for a tag file or a failed compile.
   *
   * These are the names the author *wrote* (`icon`), which is what the
   * watcher resolves against the tag scan — not the emitted class name and
   * not the gensym'd binding a discovered tag lowers to.
   */
  usedTags: string[];
  /** Every output path this call touched (page `.html`, its `.map`), for `knownOutputs` bookkeeping. */
  outputs: string[];
}

/**
 * Compiles and writes one discovered tag file (task 1.7).
 *
 * A tag file's output is a `.ts` component module (`tagExtension`), not a
 * template — an Angular component is a class with a decorator, so there is no
 * template-only form (A3's "two output kinds"). Otherwise this mirrors
 * `buildPage`: the same overwrite guard, the same write-only-if-different, the
 * same positioned error handling — with the header in `//` form, since the
 * output is TypeScript.
 *
 * No `.map` sidecar: `compileTagModule` wraps the emitted template in a
 * decorator, so the template's own offsets no longer describe the emitted
 * file, and a map claiming otherwise would be worse than none.
 */
function compileTagFile(
  mxPath: string,
  config: AngularConfig,
  knownOutputs: Set<string>,
): CompileOneResult {
  const outputPath = outputPathFor(mxPath, config.tagExtension);
  const sourceBasename = basename(mxPath);
  // The header's second line names the `imports:` a *page*'s own TypeScript
  // needs; a tag module writes its own `imports:` array, so there is nothing
  // for the author to add and the list is empty.
  const header = buildHeader(sourceBasename, sourceBasename, [], "ts");

  try {
    const customTags = getCustomTags(mxPath, { host: "angular" });
    const result = compileTagModuleFile(mxPath, {
      customTags,
      tagSelectorPrefix: config.tagSelectorPrefix,
    });
    const content = header + result.code;

    if (existsSync(outputPath)) {
      const overwriteError = checkOverwriteGuard(outputPath);
      if (overwriteError) {
        return {
          ok: false,
          lines: [`${outputPath} error: ${overwriteError}`],
          errors: [
            { file: mxPath, line: 1, column: 0, message: overwriteError },
          ],
          warnings: [],
          usedTags: [],
          outputs: [],
        };
      }
    }

    const existed = existsSync(outputPath);
    const before = existed ? readFileSync(outputPath, "utf8") : undefined;
    writeIfDiffers(outputPath, content, knownOutputs);
    const wrote = before !== content;

    const lines = [`${outputPath} ${wrote ? "wrote" : "skipped (unchanged)"}`];
    const warnings = warningsFor(mxPath, result.warnings);
    for (const w of warnings) {
      const position = w.line !== undefined ? `:${w.line}:${w.column}` : "";
      lines.push(`${w.file}${position} warning: ${w.message}`);
    }

    return {
      ok: true,
      lines,
      errors: [],
      warnings,
      // A tag's own called tags are already in its emitted `imports:` array,
      // so it reports none upward: `usedTags` drives the *page* dependency
      // map, and a tag is tracked by its own path, not by its callees.
      usedTags: [],
      outputs: [outputPath],
    };
  } catch (err) {
    const positioned = err instanceof TranslateError;
    // A tag template's own error carries `file` pointing at the tag, not the
    // caller, and is reported against that file (A5).
    const errorFile = positioned && err.file ? err.file : mxPath;
    const message = positioned
      ? `${errorFile}:${err.line}:${err.column} ${err.message}`
      : `${mxPath}: ${err instanceof Error ? err.message : String(err)}`;
    const applied = applyOnError(
      outputPath,
      header,
      message,
      config.onError,
      knownOutputs,
    );
    const error: PositionedMessage = positioned
      ? {
          file: errorFile,
          line: err.line,
          column: err.column,
          message: err.message,
        }
      : { file: mxPath, message };
    return {
      ok: false,
      lines: [`${mxPath} error: ${message}`, applied.line],
      errors: applied.error
        ? [{ file: mxPath, line: 1, column: 0, message: applied.error }]
        : [error],
      warnings: [],
      usedTags: [],
      outputs: [outputPath],
    };
  }
}

/**
 * Compiles one routed file — page or tag — and applies every write/guard/
 * error policy exactly once (round 1 R-a). `knownOutputs` accumulates every
 * path this call wrote or would have written, so a caller with a live
 * `fs.watch` on the same directory can ignore its own self-triggered events
 * (round 1 R-b).
 */
export function compileOne(
  routed: { path: string; kind: "page" | "tag" },
  config: AngularConfig,
  knownOutputs: Set<string>,
): CompileOneResult {
  // A tag file routes through this same entry point (so the watcher, the
  // build and the error policy all share one path) but emits a different
  // artifact: a `.ts` component module, not a template. See the comment on
  // `compileTagFile`.
  if (routed.kind === "tag") {
    return compileTagFile(routed.path, config, knownOutputs);
  }

  const mxPath = routed.path;
  const outputPath = outputPathFor(mxPath, config.pageExtension);
  const mapPath = `${outputPath}.map`;
  const sourceBasename = basename(mxPath);
  const tsFilename = sourceBasename.replace(/\.mx$/, ".ts");
  const outputs = [outputPath, mapPath];

  try {
    const customTags = getCustomTags(mxPath, { host: "angular" });
    const result = compileFile(mxPath, {
      customTags,
      tagSelectorPrefix: config.tagSelectorPrefix,
    });
    const header = buildHeader(sourceBasename, tsFilename, result.usedTags);
    const usedTagNames = result.usedTags.map((t) => t.name);
    const content = header + result.code;

    if (existsSync(outputPath)) {
      const overwriteError = checkOverwriteGuard(outputPath);
      if (overwriteError) {
        return {
          ok: false,
          lines: [`${outputPath} error: ${overwriteError}`],
          errors: [
            { file: mxPath, line: 1, column: 0, message: overwriteError },
          ],
          warnings: [],
          usedTags: usedTagNames,
          outputs: [],
        };
      }
    }

    const existed = existsSync(outputPath);
    const before = existed ? readFileSync(outputPath, "utf8") : undefined;
    writeIfDiffers(outputPath, content, knownOutputs);
    const wrote = before !== content;

    // Gate the map write behind the same bytes-differ check as the output
    // (round 1 R-b): an unconditional map write on every compile — even a
    // no-op recompile — is itself a self-triggering fs event.
    const mapContent = `${JSON.stringify(
      buildMap(sourceBasename, basename(outputPath), result.map),
      null,
      2,
    )}\n`;
    const mapExisted = existsSync(mapPath);
    const mapBefore = mapExisted ? readFileSync(mapPath, "utf8") : undefined;
    if (mapBefore !== mapContent) {
      writeMap(mapPath, JSON.parse(mapContent));
    }
    knownOutputs.add(mapPath);

    const lines = [`${outputPath} ${wrote ? "wrote" : "skipped (unchanged)"}`];
    const warnings = warningsFor(mxPath, result.warnings);
    for (const w of warnings) {
      const position = w.line !== undefined ? `:${w.line}:${w.column}` : "";
      lines.push(`${w.file}${position} warning: ${w.message}`);
    }

    return {
      ok: true,
      lines,
      errors: [],
      warnings,
      usedTags: usedTagNames,
      outputs,
    };
  } catch (err) {
    const positioned = err instanceof TranslateError;
    // A tag template's own error carries `file` (A5) — a call site inside
    // a discovered tag's sidecar `transform`, for instance — and must be
    // reported against that file, not the page that called it.
    const errorFile = positioned && err.file ? err.file : mxPath;
    // `@marko/compiler`'s own Babel plugin invocation prefixes a thrown
    // error's `.message` with the file path (`${filename}: ...`) before it
    // propagates out of `compileSync` — this affects both a `TranslateError`
    // (`fail()`'s own message text) and a plain `Error`, so the prefix must
    // be stripped from `err.message` itself before it's reused for either
    // display or the structured `errors` array, or the file path shows up
    // twice in one line (`errorFile:line:col error: ${errorFile}: msg`).
    const rawMessage = err instanceof Error ? err.message : String(err);
    const strippedMessage = rawMessage.startsWith(`${errorFile}: `)
      ? rawMessage.slice(errorFile.length + 2)
      : rawMessage;
    // The on-page error template (written by applyOnError -> errorTemplate)
    // needs the filename too, not just line:column — round 2 finding 2:
    // stripping the Babel-added `${errorFile}: ` prefix above must not
    // also drop the filename from what actually lands in the `<pre>`.
    const message = positioned
      ? `${errorFile}:${err.line}:${err.column} ${strippedMessage}`
      : `${errorFile}: ${strippedMessage}`;
    const header = buildHeader(sourceBasename, tsFilename, []);
    const { error: overwriteError, line: onErrorLine } = applyOnError(
      outputPath,
      header,
      message,
      config.onError,
      knownOutputs,
    );
    if (overwriteError) {
      return {
        ok: false,
        lines: [onErrorLine],
        errors: [{ file: mxPath, line: 1, column: 0, message: overwriteError }],
        warnings: [],
        usedTags: [],
        outputs: [],
      };
    }
    return {
      ok: false,
      lines: [
        onErrorLine,
        `${errorFile}:${positioned ? `${err.line}:${err.column}` : "1:0"} error: ${strippedMessage}`,
      ],
      errors: positioned
        ? [
            {
              file: errorFile,
              line: err.line,
              column: err.column,
              message: strippedMessage,
            },
          ]
        : [{ file: mxPath, message: strippedMessage }],
      warnings: [],
      usedTags: [],
      outputs,
    };
  }
}

/** Removes a page's outputs and forgets them (round 1 R-d: a vanished .mx with `onError: "delete"`). Never touches a hand-written file lacking the generated header. */
export function removeOutputsFor(
  mxPath: string,
  config: AngularConfig,
  knownOutputs: Set<string>,
): { line: string } {
  const outputPath = outputPathFor(mxPath, config.pageExtension);
  const mapPath = `${outputPath}.map`;
  if (!existsSync(outputPath)) {
    knownOutputs.delete(outputPath);
    knownOutputs.delete(mapPath);
    return { line: `${outputPath} skipped (already gone)` };
  }
  const overwriteError = checkOverwriteGuard(outputPath);
  if (overwriteError) {
    return { line: `${outputPath} error: ${overwriteError}` };
  }
  if (isSymlink(outputPath)) {
    return {
      line: `${outputPath} error: refusing to delete through a symlink: ${outputPath}`,
    };
  }
  unlinkSync(outputPath);
  if (existsSync(mapPath) && !isSymlink(mapPath)) unlinkSync(mapPath);
  knownOutputs.delete(outputPath);
  knownOutputs.delete(mapPath);
  return { line: `${outputPath} skipped (deleted; source removed)` };
}

export function build(projectDir: string): BuildResult {
  const config = readAngularConfig(projectDir);
  const { files, overlapWarnings, diagnostics } = discoverFiles(
    projectDir,
    config,
  );

  const errors: PositionedMessage[] = [];
  const warnings: PositionedMessage[] = [
    ...overlapWarnings.map((file) => ({
      file,
      line: 1,
      column: 0,
      message:
        "matched by both `include` and the tag index; the tag-index route wins",
    })),
    ...diagnostics.map((d) => ({ file: d.file, message: d.message })),
  ];

  const knownOutputs = new Set<string>();
  for (const routed of files) {
    // Belt and suspenders: discoverFiles() already filters to projectDir,
    // but a build() caller other than the CLI could hand in a file list of
    // its own — never compile, and never write beside, a path outside the
    // project this build was pointed at.
    if (!isInside(projectDir, routed.path)) {
      errors.push({
        file: routed.path,
        message: "outside the project directory; refusing to compile",
      });
      continue;
    }
    const result = compileOne(routed, config, knownOutputs);
    errors.push(...result.errors);
    warnings.push(...result.warnings);
  }

  return { ok: errors.length === 0, errors, warnings };
}
