/**
 * `mx-angular build` (design note A3): compiles every routed `.mx` file to
 * its Angular output, applying the `onError` policy and writing only when
 * bytes differ.
 */

import {
  existsSync,
  lstatSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join } from "node:path";
import { getCustomTags, type MxWarning, TranslateError } from "@mxlang/core";
import { type AngularConfig, readAngularConfig } from "./config.ts";
import { discoverFiles, isInside } from "./discover.ts";
import { buildHeader, hasGeneratedHeader } from "./header.ts";
import { compileFile } from "./index.ts";
import { buildMap, writeMap } from "./map-file.ts";

/**
 * Refuses to write over an output that already exists and was not
 * generated by this tool (A3: "the emitted `.ts` must not collide with a
 * hand-written one" — applied to every output kind, not only tag modules,
 * so a hand-written page template is never clobbered either). Returns an
 * error message, or `undefined` if writing is safe.
 */
export function checkOverwriteGuard(outputPath: string): string | undefined {
  if (!existsSync(outputPath)) return undefined;
  const existing = readFileSync(outputPath, "utf8");
  if (hasGeneratedHeader(existing)) return undefined;
  return `refusing to overwrite \`${outputPath}\`, which MX did not generate; rename the tag file or the existing module.`;
}

export interface PositionedMessage {
  file: string;
  /** Absent for a failure with no source position (a thrown non-`TranslateError`). */
  line?: number;
  column?: number;
  message: string;
}

export interface BuildResult {
  ok: boolean;
  errors: PositionedMessage[];
  warnings: PositionedMessage[];
}

function outputPathFor(mxPath: string, extension: string): string {
  const base = basename(mxPath, ".mx");
  return join(dirname(mxPath), `${base}${extension}`);
}

/**
 * Whether `path` is a symlink. `writeFileSync`/`unlinkSync` both follow a
 * symlink to its target by default; every output path here is derived from
 * a discovered `.mx` file's own directory, so a symlinked output slot would
 * let a compile silently write (or delete) outside the project tree it was
 * pointed at.
 */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

function writeIfDiffers(path: string, content: string): void {
  if (isSymlink(path)) {
    throw new Error(`refusing to write through a symlink: ${path}`);
  }
  if (existsSync(path)) {
    const existing = readFileSync(path, "utf8");
    if (existing === content) return;
  }
  writeFileSync(path, content, "utf8");
}

/** The visible `<pre>` error template written on a cold start (A3's `onError` table). */
function errorTemplate(message: string): string {
  const escaped = message
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<!-- mx-angular: compile error -->\n<pre style="white-space:pre-wrap;color:#b00">${escaped}</pre>\n`;
}

/**
 * Applies the `onError` policy for a failed compile. Returns an overwrite-
 * guard error message when the policy would have written or deleted a
 * hand-written file — every branch (`delete`'s `unlinkSync`, `error-
 * template`'s and `keep-last`'s cold-start `writeIfDiffers`) checks
 * `checkOverwriteGuard` first, so a compile error never clobbers a file MX
 * did not generate; that would otherwise be a wrong error message ("this
 * is now broken because your template has an error") on someone else's
 * file, on every one of the three modes.
 */
function applyOnError(
  outputPath: string,
  headerPrefix: string,
  message: string,
  onError: AngularConfig["onError"],
): string | undefined {
  const hadPrevious = existsSync(outputPath);
  const generatedByUs = hadPrevious
    ? hasGeneratedHeader(readFileSync(outputPath, "utf8"))
    : false;

  if (onError === "delete") {
    if (hadPrevious) {
      if (!generatedByUs) return checkOverwriteGuard(outputPath);
      if (isSymlink(outputPath)) {
        throw new Error(`refusing to delete through a symlink: ${outputPath}`);
      }
      unlinkSync(outputPath);
    }
    return undefined;
  }

  if (onError === "error-template") {
    if (hadPrevious && !generatedByUs) return checkOverwriteGuard(outputPath);
    writeIfDiffers(outputPath, headerPrefix + errorTemplate(message));
    return undefined;
  }

  // keep-last (default): leave a previous good output; write the error
  // template only on a cold start (no previous output at all), or when the
  // existing file is neither ours nor a good previous output — but never
  // over a file MX did not generate.
  if (!hadPrevious) {
    writeIfDiffers(outputPath, headerPrefix + errorTemplate(message));
    return undefined;
  }
  if (!generatedByUs) {
    return checkOverwriteGuard(outputPath);
  }
  return undefined;
}

/** Compiles and writes one page file. Returns any errors/warnings, positioned. */
function buildPage(
  mxPath: string,
  config: AngularConfig,
): { error?: PositionedMessage; warnings: PositionedMessage[] } {
  const outputPath = outputPathFor(mxPath, config.pageExtension);
  const mapPath = `${outputPath}.map`;
  const sourceBasename = basename(mxPath);
  const tsFilename = basename(mxPath).replace(/\.mx$/, ".ts");

  try {
    // Discovered per file, matching every other integration (the Bun
    // loaders, the Vite plugin, mx-tsc): which tags a template may call
    // follows from where the template lives, not from the whole build.
    const customTags = getCustomTags(mxPath);
    const result = compileFile(mxPath, { customTags });
    const header = buildHeader(sourceBasename, tsFilename, result.usedTags);
    const content = header + result.code;

    const overwriteError = existsSync(outputPath)
      ? checkOverwriteGuard(outputPath)
      : undefined;
    if (overwriteError) {
      return {
        error: { file: mxPath, line: 1, column: 0, message: overwriteError },
        warnings: [],
      };
    }

    writeIfDiffers(outputPath, content);
    writeMap(
      mapPath,
      buildMap(sourceBasename, basename(outputPath), result.map),
    );
    const warnings = warningsFor(mxPath, result.warnings);
    return { warnings };
  } catch (err) {
    const positioned = err instanceof TranslateError;
    // A tag template's own error carries `file` (A5) — a call site inside
    // a discovered tag's sidecar `transform`, for instance — and must be
    // reported against that file, not the page that called it.
    const errorFile = positioned && err.file ? err.file : mxPath;
    const message = positioned
      ? `${errorFile}:${err.line}:${err.column} ${err.message}`
      : `${mxPath}: ${err instanceof Error ? err.message : String(err)}`;
    const header = buildHeader(sourceBasename, tsFilename, []);
    const overwriteError = applyOnError(
      outputPath,
      header,
      message,
      config.onError,
    );
    if (overwriteError) {
      return {
        error: { file: mxPath, line: 1, column: 0, message: overwriteError },
        warnings: [],
      };
    }
    return {
      error: positioned
        ? {
            file: errorFile,
            line: err.line,
            column: err.column,
            message: err.message,
          }
        : { file: mxPath, message },
      warnings: [],
    };
  }
}

function warningsFor(file: string, warnings: MxWarning[]): PositionedMessage[] {
  return warnings.map((w) => ({
    file,
    line: w.line,
    column: w.column,
    message: w.message,
  }));
}

/**
 * A discovered tag file. 1.5a does not yet have a route to emit an Angular
 * component *class* from a `.mx` tag file — that is task 1.7's tag-unit
 * compile route (`@mxlang/core`'s `template-tag.ts` has no Angular-side
 * consumer yet: `compile()` only emits a template string, never a component
 * module). Reported as a positioned error naming the missing task rather
 * than silently emitting a template where a component module belongs.
 */
function buildTag(mxPath: string): PositionedMessage {
  return {
    file: mxPath,
    line: 1,
    column: 0,
    message:
      "tag files are not yet compiled by mx-angular: component-module emission needs task 1.7 (tag-unit compile route), not yet landed for the angular host",
  };
}

export function build(projectDir: string): BuildResult {
  const config = readAngularConfig(projectDir);
  const { files, overlapWarnings, diagnostics } = discoverFiles(
    projectDir,
    config,
  );

  const errors: PositionedMessage[] = [];
  const warnings: PositionedMessage[] = [
    ...overlapWarnings.map((file) => ({
      file,
      line: 1,
      column: 0,
      message:
        "matched by both `include` and the tag index; the tag-index route wins",
    })),
    ...diagnostics.map((d) => ({ file: d.file, message: d.message })),
  ];

  for (const routed of files) {
    // Belt and suspenders: discoverFiles() already filters to projectDir,
    // but a build() caller other than the CLI could hand in a file list of
    // its own — never compile, and never write beside, a path outside the
    // project this build was pointed at.
    if (!isInside(projectDir, routed.path)) {
      errors.push({
        file: routed.path,
        message: "outside the project directory; refusing to compile",
      });
      continue;
    }
    if (routed.kind === "tag") {
      errors.push(buildTag(routed.path));
      continue;
    }
    const { error, warnings: pageWarnings } = buildPage(routed.path, config);
    if (error) errors.push(error);
    warnings.push(...pageWarnings);
  }

  return { ok: errors.length === 0, errors, warnings };
}
