/**
 * The generated-file header comment (design note A3, "Output mapping").
 *
 * Every emitted `.html` file starts with this comment, which is both what a
 * human reads and the guard against overwriting a hand-written file (A3:
 * "the emitted `.ts` must not collide with a hand-written one" — the same
 * guard applies to a page's own `.html` output, so a hand-written template
 * is never clobbered either).
 */

const MARKER = "Generated by @mxlang/angular from";

/** `UserCard` -> `user-card`; mirrors `emitter.ts`'s own `kebabCase`, used for the same import-path shape A3's example shows. */
function kebabCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

/**
 * Builds the full header comment for `sourceBasename`: A3's first line
 * always, plus its second "Add to x.component.ts: ..." line when
 * `usedTags` is non-empty (the compiled template called at least one MX
 * tag it cannot import for the caller).
 */
export function buildHeader(
  sourceBasename: string,
  tsFilename: string,
  usedTags: string[],
): string {
  let header = `<!-- ${MARKER} ${sourceBasename}. Do not edit. -->\n`;
  if (usedTags.length > 0) {
    const lines = usedTags
      .map(
        (name) =>
          `\`import ${name} from "./tags/${kebabCase(name)}";\` and \`imports: [${name}]\``,
      )
      .join(", ");
    header += `<!-- Add to ${tsFilename}: ${lines} -->\n`;
  }
  return header;
}

/**
 * Whether `content` starts with a header this tool generated — either
 * comment style, since `checkOverwriteGuard` also guards a `tagExtension`
 * output (a `.ts` file, `//`-commented) once task 1.7 starts writing one,
 * even though `buildHeader` only builds the `.html` (`<!--`) form today.
 */
export function hasGeneratedHeader(content: string): boolean {
  return (
    content.startsWith(`<!-- ${MARKER} `) || content.startsWith(`// ${MARKER} `)
  );
}
