/**
 * The generated-file header comment (design note A3, "Output mapping").
 *
 * Every emitted `.html` file starts with this comment, which is both what a
 * human reads and the guard against overwriting a hand-written file (A3:
 * "the emitted `.ts` must not collide with a hand-written one" — the same
 * guard applies to a page's own `.html` output, so a hand-written template
 * is never clobbered either).
 */

const MARKER = "Generated by @mxlang/angular from";

/** One MX tag a compiled template called, as the caller's TypeScript names it. */
export interface UsedTag {
  className: string;
  specifier: string;
}

/**
 * Builds the full header comment for `sourceBasename`: A3's first line
 * always, plus its second "Add to x.component.ts: ..." line when
 * `usedTags` is non-empty (the compiled template called at least one MX
 * tag it cannot import for the caller).
 *
 * `style` picks the comment syntax: a page's emitted `.html` takes `<!-- -->`,
 * a tag file's emitted `.ts` module takes `//` (A3's two output kinds).
 */
export function buildHeader(
  sourceBasename: string,
  tsFilename: string,
  usedTags: UsedTag[],
  style: "html" | "ts" = "html",
): string {
  const open = style === "ts" ? "// " : "<!-- ";
  const close = style === "ts" ? "" : " -->";
  let header = `${open}${MARKER} ${sourceBasename}. Do not edit.${close}\n`;
  if (usedTags.length > 0) {
    const lines = usedTags
      .map(
        (tag) =>
          `\`import ${tag.className} from "${tag.specifier}";\` and \`imports: [${tag.className}]\``,
      )
      .join(", ");
    header += `${open}Add to ${tsFilename}: ${lines}${close}\n`;
  }
  return header;
}

/**
 * Whether `content` starts with a header this tool generated — either
 * comment style, because all three output kinds are guarded: a page's
 * `.html` (`<!--`), and a tag module's and a `.ng.mx` module's `.ts`
 * (`//`).
 */
export function hasGeneratedHeader(content: string): boolean {
  return (
    content.startsWith(`<!-- ${MARKER} `) || content.startsWith(`// ${MARKER} `)
  );
}
