import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { build, checkOverwriteGuard } from "../src/build.ts";
import { runCli } from "../src/cli.ts";
import { readAngularConfig } from "../src/config.ts";
import { discoverFiles } from "../src/discover.ts";

let projectDir: string;

function writeProject(files: Record<string, string>): void {
  for (const [path, content] of Object.entries(files)) {
    const full = join(projectDir, path);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, content, "utf8");
  }
}

beforeEach(() => {
  projectDir = mkdtempSync(join(tmpdir(), "mx-angular-test-"));
});

afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
});

describe("readAngularConfig", () => {
  it("applies A3's defaults when mx.angular is absent", () => {
    writeProject({ "package.json": JSON.stringify({ name: "x" }) });
    const config = readAngularConfig(projectDir);
    expect(config).toEqual({
      include: [],
      pageExtension: ".html",
      tagExtension: ".ts",
      tagSelectorPrefix: "mx-",
      onError: "keep-last",
    });
  });

  it("reads explicit values", () => {
    writeProject({
      "package.json": JSON.stringify({
        name: "x",
        mx: {
          host: "angular",
          angular: {
            include: ["src/**/*.mx"],
            pageExtension: ".ng.html",
            tagExtension: ".tag.ts",
            tagSelectorPrefix: "app-",
            onError: "delete",
          },
        },
      }),
    });
    const config = readAngularConfig(projectDir);
    expect(config).toEqual({
      include: ["src/**/*.mx"],
      pageExtension: ".ng.html",
      tagExtension: ".tag.ts",
      tagSelectorPrefix: "app-",
      onError: "delete",
    });
  });

  it("rejects an invalid onError value", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { angular: { onError: "nope" } },
      }),
    });
    expect(() => readAngularConfig(projectDir)).toThrow(/onError/);
  });

  it("rejects an unrecognized key, positioned against package.json", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { angular: { typo: true } },
      }),
    });

    let caught: unknown;
    try {
      readAngularConfig(projectDir);
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(Error);
    const err = caught as {
      message: string;
      line?: number;
      column?: number;
      file?: string;
    };
    expect(err.message).toMatch(/`mx\.angular\.typo` is not a recognized key/);
    expect(err.line).toBe(1);
    expect(err.column).toBe(0);
    expect(err.file).toBe(join(projectDir, "package.json"));
  });
});

describe("build: page routing", () => {
  it("compiles a page file to pageExtension beside the source, with the header and a sidecar map", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>Hello, ${input.name}!</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
    const html = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    expect(html).toContain(
      "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->",
    );
    expect(html).toContain("{{ input.name }}");

    const map = JSON.parse(
      readFileSync(join(projectDir, "src/greeting.html.map"), "utf8"),
    );
    expect(map.version).toBe(3);
    expect(map.sources).toEqual(["greeting.mx"]);
  });
});

describe("build: tag routing", () => {
  it("routes a tags/-discovered .mx file as a tag, not a page, even outside include", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<div>home</div>",
      "src/tags/badge.mx": "<span>${input.text}</span>",
    });

    const result = build(projectDir);

    // Tag files are not yet emittable (task 1.7 not landed) — this is the
    // expected positioned error, not a page compile.
    expect(result.errors.some((e) => e.file.endsWith("badge.mx"))).toBe(true);
    expect(result.errors.some((e) => /task 1\.7/.test(e.message))).toBe(true);
    expect(existsSync(join(projectDir, "src/tags/badge.html"))).toBe(false);

    // The page file still compiles fine.
    expect(existsSync(join(projectDir, "src/pages/home.html"))).toBe(true);
  });

  it("warns once when include and the tag index both claim a path", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/badge.mx": "<span>${input.text}</span>",
    });

    const result = build(projectDir);

    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]?.file).toMatch(/badge\.mx$/);
    expect(result.warnings[0]?.message).toMatch(/tag index/);
  });

  it("resolves a discovered lowercase tag (sidecar transform) when compiling a page that calls it", () => {
    // `<badge/>` is lowercase: with no discovered custom tag registered,
    // @mxlang/core's lower.ts treats an unbound lowercase tag as a hard
    // "unknown tag" compile error (it is never mistaken for an HTML
    // element) — compiling this page without threading the discovered tag
    // index into compile() would fail outright. A sidecar `transform`
    // returning plain IR (a macro), rather than a bare template, is what
    // this test can exercise directly: a *template* tag call goes through
    // a different, already-known-limited path (an injected import node
    // this host's step-1 emitter rejects — see the design note's A3/A5;
    // out of scope here).
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<badge/>",
      "src/tags/badge.tag.ts": `
        export default {
          transform(call, ctx) {
            return [ctx.build.text("BADGE")];
          },
        };
      `,
    });

    const result = build(projectDir);

    expect(result.errors.filter((e) => e.file.endsWith("home.mx"))).toEqual([]);
    const html = readFileSync(join(projectDir, "src/pages/home.html"), "utf8");
    expect(html).toContain("BADGE");
  });

  it("reports a tag template's own compile error against the tag file, not the caller (A5)", () => {
    // `badge.mx` here is a *template* tag (no sidecar) with a body error
    // core catches during its own tag-unit metadata compile
    // (template-tag.ts's metadataForTemplate) — a construct core itself
    // rejects (a `<for>` needing tag params), not an Angular-emitter
    // rejection. core's TranslateError carries `file: badge.mx` for
    // exactly this case (A5); build.ts must report against that file, not
    // home.mx, which merely called it.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<badge/>",
      "src/tags/badge.mx": "<for from=1 to=10><div>x</div></for>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const tagError = result.errors.find((e) => e.file.endsWith("badge.mx"));
    expect(tagError).toBeDefined();
    expect(result.errors.some((e) => e.file.endsWith("home.mx"))).toBe(false);
  });

  it("does not claim an mx.tags entry scoped to a different host", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [{ dir: "widgets", hosts: ["solid"] }],
        },
      }),
      "widgets/gadget.mx": "<span>gadget</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(files.some((f) => f.path.endsWith("gadget.mx"))).toBe(false);

    // build() only ever writes beside a page's own include match, so no
    // output for the excluded tag either.
    build(projectDir);
    expect(existsSync(join(projectDir, "widgets/gadget.html"))).toBe(false);
  });

  it("claims an mx.tags entry scoped to angular, or with no hosts restriction at all", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [
            { dir: "widgets-scoped", hosts: ["angular"] },
            { dir: "widgets-unscoped" },
          ],
        },
      }),
      "widgets-scoped/gadget.mx": "<span>gadget</span>",
      "widgets-unscoped/thing.mx": "<span>thing</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(
      files.some((f) => f.path.endsWith("gadget.mx") && f.kind === "tag"),
    ).toBe(true);
    expect(
      files.some((f) => f.path.endsWith("thing.mx") && f.kind === "tag"),
    ).toBe(true);
  });

  it("discovers a tags/ directory two levels below a nested package boundary", () => {
    // proj/a has no package.json; proj/a/b does. A tags/ dir under
    // proj/a/b must still be discovered as b's own tag index — the walk
    // must not stop merely because it passed through a's non-package
    // directory on the way, nor because b's own package.json marks a
    // separate scan root: it changes which mx.tags applies, not whether
    // the walk continues.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["a/b/pages/**/*.mx"] } },
      }),
      "a/b/package.json": JSON.stringify({ name: "nested" }),
      "a/b/pages/home.mx": "<div>home</div>",
      "a/b/tags/y.mx": "<span>y</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    const tag = files.find((f) => f.path.endsWith("a/b/tags/y.mx"));
    expect(tag).toBeDefined();
    expect(tag?.kind).toBe("tag");

    // Misrouted as a page would have emitted a/b/tags/y.html — must not.
    build(projectDir);
    expect(existsSync(join(projectDir, "a/b/tags/y.html"))).toBe(false);
  });
});

describe("build: byte-differ no-write", () => {
  it("does not rewrite the output file when compiled bytes are unchanged", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
    });

    build(projectDir);
    const outputPath = join(projectDir, "src/greeting.html");
    const before = readFileSync(outputPath, "utf8");

    build(projectDir);
    const after = readFileSync(outputPath, "utf8");

    expect(after).toBe(before);
  });

  it("refuses to overwrite a hand-written .html file at the page's own output path", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
      "src/greeting.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });
});

describe("checkOverwriteGuard", () => {
  it("refuses to overwrite a tagExtension output lacking the generated header", () => {
    writeProject({ "tags/card.ts": "export class Card {}\n" });
    const outputPath = join(projectDir, "tags/card.ts");

    const message = checkOverwriteGuard(outputPath);

    expect(message).toMatch(/refusing to overwrite/);
    expect(message).toContain("card.ts");
  });

  it("allows overwriting an output this tool generated", () => {
    writeProject({
      "tags/card.ts":
        "// Generated by @mxlang/angular from card.mx. Do not edit.\nexport class Card {}\n",
    });
    const outputPath = join(projectDir, "tags/card.ts");

    expect(checkOverwriteGuard(outputPath)).toBeUndefined();
  });

  it("allows writing when no output exists yet", () => {
    const outputPath = join(projectDir, "tags/new.ts");
    expect(checkOverwriteGuard(outputPath)).toBeUndefined();
  });
});

describe("security: symlinks and path escape", () => {
  it("does not follow a symlinked tags/ directory (may point outside the project)", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      mkdirSync(join(outsideDir, "tags"), { recursive: true });
      writeFileSync(
        join(outsideDir, "tags/leak.mx"),
        "<span>leak</span>",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
        }),
        "src/home.mx": "<div>home</div>",
      });
      symlinkSync(join(outsideDir, "tags"), join(projectDir, "tags"), "dir");

      const { files } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(files.some((f) => f.path.includes("leak.mx"))).toBe(false);
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });

  it("refuses to write through a symlinked output path", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      // A generated-looking header passes checkOverwriteGuard, so the write
      // actually reaches writeIfDiffers's own symlink check — the property
      // under test.
      writeFileSync(
        join(outsideDir, "greeting.html"),
        "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->\noutside",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
        }),
        "src/greeting.mx": "<div>hi, changed</div>",
      });
      symlinkSync(
        join(outsideDir, "greeting.html"),
        join(projectDir, "src/greeting.html"),
        "file",
      );

      const result = build(projectDir);

      expect(result.ok).toBe(false);
      expect(result.errors.some((e) => /symlink/.test(e.message))).toBe(true);

      // The outside file must be untouched.
      expect(readFileSync(join(outsideDir, "greeting.html"), "utf8")).toBe(
        "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->\noutside",
      );
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });

  it("drops an mx.tags entry whose dir resolves outside the project", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      mkdirSync(join(outsideDir, "leaked-tags"), { recursive: true });
      writeFileSync(
        join(outsideDir, "leaked-tags/leak.mx"),
        "<span>leak</span>",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: {
            host: "angular",
            angular: { include: ["src/**/*.mx"] },
            // An absolute path outside projectDir is exactly the case
            // isInside() must reject — `mx.tags[].dir` is otherwise
            // resolved verbatim, with no containment check of its own.
            tags: [{ dir: join(outsideDir, "leaked-tags") }],
          },
        }),
        "src/home.mx": "<div>home</div>",
      });

      const { files } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(files.some((f) => f.path.includes("leak.mx"))).toBe(false);
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });
});

describe("onError policy (A3's 3x2 table)", () => {
  function writeFailingProject() {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
    });
  }

  it("keep-last: cold start writes a visible error template", () => {
    writeFailingProject();
    build(projectDir);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toContain("<pre");
    expect(html).toContain("compile error");
  });

  it("keep-last: leaves a previous good output in place on a later error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/flaky.mx": "<div>good</div>",
    });
    build(projectDir);
    const goodOutput = readFileSync(join(projectDir, "src/flaky.html"), "utf8");

    writeFileSync(
      join(projectDir, "src/flaky.mx"),
      "<for from=1 to=10 step=0><div>x</div></for>",
      "utf8",
    );
    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const afterOutput = readFileSync(
      join(projectDir, "src/flaky.html"),
      "utf8",
    );
    expect(afterOutput).toBe(goodOutput);
  });

  it("error-template: overwrites even a previous good output", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "error-template" },
        },
      }),
      "src/flaky.mx": "<div>good</div>",
    });
    build(projectDir);

    writeFileSync(
      join(projectDir, "src/flaky.mx"),
      "<for from=1 to=10 step=0><div>x</div></for>",
      "utf8",
    );
    build(projectDir);

    const output = readFileSync(join(projectDir, "src/flaky.html"), "utf8");
    expect(output).toContain("compile error");
  });

  it("delete: removes any existing output and writes nothing on cold start", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "delete" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
    });
    build(projectDir);
    expect(existsSync(join(projectDir, "src/broken.html"))).toBe(false);
  });

  it("keep-last: never overwrites a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });

  it("error-template: never overwrites a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "error-template" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });

  it("delete: never deletes a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "delete" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    expect(existsSync(join(projectDir, "src/broken.html"))).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });
});

describe("mx-angular map", () => {
  it("prints the source file, and says fine-grained mapping isn't available yet, since compile()'s map has no real positions", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
    });
    build(projectDir);

    const logs: string[] = [];
    const originalLog = console.log;
    console.log = (msg: string) => logs.push(msg);
    try {
      const exitCode = runCli([
        "map",
        `${join(projectDir, "src/greeting.html")}:1:0`,
      ]);
      expect(exitCode).toBe(0);
    } finally {
      console.log = originalLog;
    }

    expect(logs).toEqual([
      "greeting.mx",
      "no fine-grained mapping yet (mappings empty); see the header comment",
    ]);
  });

  it("fails with a clear message when no sidecar exists", () => {
    const originalError = console.error;
    const errors: string[] = [];
    console.error = (msg: string) => errors.push(msg);
    try {
      const exitCode = runCli([
        "map",
        `${join(projectDir, "src/missing.html")}:1:0`,
      ]);
      expect(exitCode).toBe(1);
    } finally {
      console.error = originalError;
    }
    expect(errors[0]).toMatch(/could not read/);
  });
});
