import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  build,
  checkOverwriteGuard,
  compileOne,
  positionOf,
} from "../src/build.ts";
import { runCli } from "../src/cli.ts";
import { type AngularConfig, readAngularConfig } from "../src/config.ts";
import { discoverFiles } from "../src/discover.ts";
import { EVENT_HELPER_MEMBERS } from "../src/emitter.ts";
import { testTargetLookupWithSegments } from "./test-targets.ts";

let projectDir: string;

function writeProject(files: Record<string, string>): void {
  for (const [path, content] of Object.entries(files)) {
    const full = join(projectDir, path);
    mkdirSync(join(full, ".."), { recursive: true });
    writeFileSync(full, content, "utf8");
  }
}

beforeEach(() => {
  projectDir = mkdtempSync(join(tmpdir(), "mx-angular-test-"));
});

afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
});

describe("readAngularConfig", () => {
  it("applies A3's defaults when mx.angular is absent", () => {
    writeProject({ "package.json": JSON.stringify({ name: "x" }) });
    const config = readAngularConfig(projectDir);
    expect(config).toEqual({
      include: [],
      pageExtension: ".html",
      tagExtension: ".ts",
      ngExtension: ".ts",
      tagSelectorPrefix: "mx-",
      onError: "keep-last",
      diagnostics: "idle",
    });
  });

  it("reads explicit values", () => {
    writeProject({
      "package.json": JSON.stringify({
        name: "x",
        mx: {
          host: "angular",
          angular: {
            include: ["src/**/*.mx"],
            pageExtension: ".ng.html",
            tagExtension: ".tag.ts",
            tagSelectorPrefix: "app-",
            onError: "delete",
            diagnostics: "save",
          },
        },
      }),
    });
    const config = readAngularConfig(projectDir);
    expect(config).toEqual({
      include: ["src/**/*.mx"],
      pageExtension: ".ng.html",
      tagExtension: ".tag.ts",
      ngExtension: ".ts",
      tagSelectorPrefix: "app-",
      onError: "delete",
      diagnostics: "save",
    });
  });

  it.each(["idle", "save", "off"] as const)(
    "accepts mx.angular.diagnostics = %s",
    (mode) => {
      writeProject({
        "package.json": JSON.stringify({
          mx: { angular: { diagnostics: mode } },
        }),
      });
      expect(readAngularConfig(projectDir).diagnostics).toBe(mode);
    },
  );

  it.each([
    ["an unknown mode", "sometimes"],
    ["a boolean", false],
    ["a number", 1],
    ["null", null],
  ])("rejects mx.angular.diagnostics set to %s", (_label, value) => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { angular: { diagnostics: value } },
      }),
    });
    expect(() => readAngularConfig(projectDir)).toThrow(
      /`mx\.angular\.diagnostics` must be one of "idle", "save" or "off"/,
    );
  });

  it("rejects an invalid onError value", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { angular: { onError: "nope" } },
      }),
    });
    expect(() => readAngularConfig(projectDir)).toThrow(/onError/);
  });

  it("rejects an unrecognized key, positioned against package.json", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { angular: { typo: true } },
      }),
    });

    let caught: unknown;
    try {
      readAngularConfig(projectDir);
    } catch (err) {
      caught = err;
    }

    expect(caught).toBeInstanceOf(Error);
    const err = caught as {
      message: string;
      line?: number;
      column?: number;
      file?: string;
    };
    expect(err.message).toMatch(/`mx\.angular\.typo` is not a recognized key/);
    expect(err.line).toBe(1);
    expect(err.column).toBe(0);
    expect(err.file).toBe(join(projectDir, "package.json"));
  });
});

describe("build: page routing", () => {
  it("compiles a page file to pageExtension beside the source, with the header and a sidecar map", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>Hello, ${input.name}!</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(true);
    expect(result.errors).toEqual([]);
    const html = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    expect(html).toContain(
      "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->",
    );
    expect(html).toContain("{{ input.name }}");

    const map = JSON.parse(
      readFileSync(join(projectDir, "src/greeting.html.map"), "utf8"),
    );
    expect(map.version).toBe(3);
    expect(map.sources).toEqual(["greeting.mx"]);
  });
});

describe("build: page header lists the event invoker members (decision 117)", () => {
  const project = {
    mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
  };

  it("adds the exact paste text to the header when the page binds a handler, and the map still lines up", () => {
    writeProject({
      "package.json": JSON.stringify(project),
      "src/form.mx": "<button onClick=cancel>x</button>",
    });

    expect(build(projectDir).ok).toBe(true);
    const html = readFileSync(join(projectDir, "src/form.html"), "utf8");
    const lines = html.split("\n");
    expect(lines[0]).toBe(
      "<!-- Generated by @mxlang/angular from form.mx. Do not edit. -->",
    );
    const members = EVENT_HELPER_MEMBERS.map((m) => `\`${m.trim()}\``).join(
      " and ",
    );
    expect(lines[1]).toBe(
      `<!-- Add to the component class in form.ts: ${members}, or extend \`MxHandlers\` (or \`MxHandlersMixin(Base)\` when the class already extends another) from "@mxlang/angular/runtime" -->`,
    );
    expect(lines[2]).toBe(
      '<button (click)="__mxOn(cancel, this, $event)">x</button>',
    );
    // A comment must not end early: no `-->` inside the member text.
    expect(lines[1]?.indexOf("-->")).toBe(
      lines[1]?.length ? lines[1].length - 3 : -1,
    );
    // The sidecar is shifted by both header lines.
    const map = JSON.parse(
      readFileSync(join(projectDir, "src/form.html.map"), "utf8"),
    );
    expect(map.mappings.startsWith(";;")).toBe(true);
  });

  it("adds no members line when the page binds no handler", () => {
    writeProject({
      "package.json": JSON.stringify(project),
      "src/plain.mx": "<div>x</div>",
    });

    expect(build(projectDir).ok).toBe(true);
    const html = readFileSync(join(projectDir, "src/plain.html"), "utf8");
    expect(html).not.toContain("__mxOn");
    expect(html.split("\n")[1]).toBe("<div>x</div>");
  });
});

describe("build: tag routing", () => {
  it("routes a tags/-discovered .mx file as a tag, not a page, even outside include", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<div>home</div>",
      "src/tags/badge.mx": "<span>${input.text}</span>",
    });

    const result = build(projectDir);

    expect(result.errors).toEqual([]);
    // A tag compiles to a `.ts` component module, never a `.html` template:
    // an Angular component is a class with a decorator (A3's two output
    // kinds), so the page extension would be the wrong artifact entirely.
    expect(existsSync(join(projectDir, "src/tags/badge.html"))).toBe(false);
    const module = readFileSync(join(projectDir, "src/tags/badge.ts"), "utf8");
    expect(module).toContain(
      "// Generated by @mxlang/angular from badge.mx. Do not edit.",
    );
    expect(module).toContain('selector: "mx-badge"');
    expect(module).toContain("export class Badge");

    // The page file still compiles fine.
    expect(existsSync(join(projectDir, "src/pages/home.html"))).toBe(true);
  });

  it("warns once when include and the tag index both claim a path", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/badge.mx": "<span>${input.text}</span>",
    });

    const result = build(projectDir);

    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]?.file).toMatch(/badge\.mx$/);
    expect(result.warnings[0]?.message).toMatch(/tag index/);
  });

  it("resolves a discovered lowercase tag (sidecar transform) when compiling a page that calls it", () => {
    // `<badge/>` is lowercase: with no discovered custom tag registered,
    // @mxlang/core's lower.ts treats an unbound lowercase tag as a hard
    // "unknown tag" compile error (it is never mistaken for an HTML
    // element) — compiling this page without threading the discovered tag
    // index into compile() would fail outright. A sidecar `transform`
    // returning plain IR (a macro), rather than a bare template, is what
    // this test can exercise directly: a *template* tag call goes through
    // a different, already-known-limited path (an injected import node
    // this host's step-1 emitter rejects — see the design note's A3/A5;
    // out of scope here).
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<badge/>",
      "src/tags/badge.tag.ts": `
        export default {
          transform(call, ctx) {
            return [ctx.build.text("BADGE")];
          },
        };
      `,
    });

    const result = build(projectDir);

    expect(result.errors.filter((e) => e.file.endsWith("home.mx"))).toEqual([]);
    const html = readFileSync(join(projectDir, "src/pages/home.html"), "utf8");
    expect(html).toContain("BADGE");
  });

  it("reports a tag template's own compile error against the tag file, not the caller (A5)", () => {
    // `badge.mx` here is a *template* tag (no sidecar) with a body error
    // core catches during its own tag-unit metadata compile
    // (template-tag.ts's metadataForTemplate) — a construct core itself
    // rejects (a `<for>` needing tag params), not an Angular-emitter
    // rejection. core's TranslateError carries `file: badge.mx` for
    // exactly this case (A5); build.ts must report against that file, not
    // home.mx, which merely called it.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/home.mx": "<badge/>",
      "src/tags/badge.mx": "<for from=1 to=10><div>x</div></for>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const tagError = result.errors.find((e) => e.file.endsWith("badge.mx"));
    expect(tagError).toBeDefined();
    expect(result.errors.some((e) => e.file.endsWith("home.mx"))).toBe(false);
  });

  it("does not claim an mx.tags entry scoped to a different host", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [{ dir: "widgets", hosts: ["solid"] }],
        },
      }),
      "widgets/gadget.mx": "<span>gadget</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(files.some((f) => f.path.endsWith("gadget.mx"))).toBe(false);

    // build() only ever writes beside a page's own include match, so no
    // output for the excluded tag either.
    build(projectDir);
    expect(existsSync(join(projectDir, "widgets/gadget.html"))).toBe(false);
  });

  it("leaves an unmatched mx.tags host unresolved under its own-only lookup", () => {
    // PR 3 round-2 ruling: own-only lookups cannot validate peer names.
    // The full-registry discovery/build/watch paths are pinned separately.
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [{ dir: "widgets", hosts: ["bogus"] }],
        },
      }),
      "src/page.mx": "<div>no call</div>",
      "widgets/gadget.mx": "<span>gadget</span>",
    });

    const result = build(projectDir);

    expect(
      result.warnings.some(
        (w) => /bogus/.test(w.message) && /package\.json$/.test(w.file),
      ),
    ).toBe(false);
  });

  it("claims an mx.tags entry scoped to angular, or with no hosts restriction at all", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [
            { dir: "widgets-scoped", hosts: ["angular"] },
            { dir: "widgets-unscoped" },
          ],
        },
      }),
      "widgets-scoped/gadget.mx": "<span>gadget</span>",
      "widgets-unscoped/thing.mx": "<span>thing</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(
      files.some((f) => f.path.endsWith("gadget.mx") && f.kind === "tag"),
    ).toBe(true);
    expect(
      files.some((f) => f.path.endsWith("thing.mx") && f.kind === "tag"),
    ).toBe(true);
  });

  it("discovers a tags/ directory two levels below a project-root-owned path", () => {
    // proj/a has no package.json; proj/a/b doesn't either. A tags/ dir
    // under proj/a/b must still be discovered as the project root's own
    // tag index — the walk must not stop merely because it passed through
    // non-package directories on the way.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["a/b/pages/**/*.mx"] } },
      }),
      "a/b/pages/home.mx": "<div>home</div>",
      "a/b/tags/y.mx": "<span>y</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    const tag = files.find((f) => f.path.endsWith("a/b/tags/y.mx"));
    expect(tag).toBeDefined();
    expect(tag?.kind).toBe("tag");

    // Misrouted as a page would have emitted a/b/tags/y.html — must not.
    build(projectDir);
    expect(existsSync(join(projectDir, "a/b/tags/y.html"))).toBe(false);
  });

  it("does not descend into a nested package's own tags/ directory", () => {
    // @mxlang/core's discoverProjectTags (packages/core/src/scan.ts) treats
    // any directory holding its own package.json, other than the project
    // root, as a separate project's boundary and never descends into it —
    // its tags belong to *its* project, not this one. This is a behavior
    // change from the angular watcher's own former walk, which continued
    // past a nested package.json (only switching which mx.tags governed
    // tags found underneath); adopting core's shared enumerator means a
    // nested package's tags/ directory is no longer discovered here.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["a/b/pages/**/*.mx"] } },
      }),
      "a/b/package.json": JSON.stringify({ name: "nested" }),
      "a/b/pages/home.mx": "<div>home</div>",
      "a/b/tags/y.mx": "<span>y</span>",
    });

    const { files } = discoverFiles(projectDir, readAngularConfig(projectDir));

    const tag = files.find((f) => f.path.endsWith("a/b/tags/y.mx"));
    expect(tag).toBeUndefined();
  });

  it("watches an empty tags/ directory and a tags/ directory whose names were all shadowed", () => {
    // tagDirectories must come from every tags/ directory core's walk
    // visited, not only from a surviving DiscoveredTag's own sourceDir:
    // neither an empty directory nor one whose every name lost to a
    // shallower tags/ directory of the same name leaves a DiscoveredTag
    // behind, but a watcher still needs to know about both.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/home.mx": "<div>home</div>",
      "tags/icon.mx": "<span>icon</span>",
      "src/tags/icon.mx": "<span>shadowed</span>",
    });
    mkdirSync(join(projectDir, "empty/tags"), { recursive: true });

    const { tagDirectories } = discoverFiles(
      projectDir,
      readAngularConfig(projectDir),
    );

    expect(tagDirectories).toContain(join(projectDir, "tags"));
    expect(tagDirectories).toContain(join(projectDir, "src/tags"));
    expect(tagDirectories).toContain(join(projectDir, "empty/tags"));
  });

  it("warns when a tags/ directory exists but cannot be read", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/home.mx": "<div>home</div>",
    });
    const tagsDir = join(projectDir, "tags");
    mkdirSync(tagsDir, { recursive: true });
    chmodSync(tagsDir, 0o000);

    try {
      // root running the suite ignores permission bits entirely, so the
      // directory stays readable and there is nothing to assert.
      const stillReadable = (() => {
        try {
          readdirSync(tagsDir);
          return true;
        } catch {
          return false;
        }
      })();
      if (stillReadable) return;

      const { diagnostics } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(
        diagnostics.some(
          (d) => d.file === tagsDir && d.message.includes("could not read"),
        ),
      ).toBe(true);
    } finally {
      chmodSync(tagsDir, 0o755);
    }
  });

  it("reports a broken package.json exactly once, from discoverProjectTags's own manifest cache", () => {
    // excludedMxTagsDirs (discover.ts) re-reads package.json itself and
    // swallows a JSON.parse failure silently. This proves the guarantee
    // that silence relies on: discoverProjectTags's own readManifest
    // already reads and diagnoses the same file, so a second diagnostic
    // from excludedMxTagsDirs's catch would double-warn for one broken
    // file. Called directly with a hand-built AngularConfig, bypassing
    // readAngularConfig (which reads package.json independently and would
    // throw on this same malformed JSON before discoverFiles ever runs —
    // see the next test for that path's own contract).
    writeProject({ "src/home.mx": "<div>home</div>" });
    writeFileSync(join(projectDir, "package.json"), "{ broken", "utf8");

    const config: AngularConfig = {
      include: ["src/**/*.mx"],
      pageExtension: ".html",
      tagExtension: ".ts",
      ngExtension: ".ts",
      tagSelectorPrefix: "mx-",
      onError: "keep-last",
      diagnostics: "idle",
    };
    const { diagnostics } = discoverFiles(projectDir, config);

    const packageJson = join(projectDir, "package.json");
    const matching = diagnostics.filter((d) => d.file === packageJson);
    expect(matching).toHaveLength(1);
    expect(matching[0]?.message).toContain("could not be parsed as JSON");
  });

  it("an invalid mx.tags shape is a fatal, positioned error — not a silently continued build", () => {
    // discoverProjectTags's own indexMxTagsEntries calls normalizeMxTags
    // uncaught: an invalid mx.tags entry throws a TranslateError through
    // discoverFiles rather than being recorded as a diagnostic. This is
    // deliberate, matching readAngularConfig's own fatal-on-bad-config
    // contract elsewhere in this file ("rejects an unrecognized key,
    // positioned against package.json") — silently continuing with an
    // incomplete tag index would be worse than failing loud. excludedMxTagsDirs's
    // own normalizeMxTags catch is therefore never reached on this path:
    // discoverProjectTags throws before excludedMxTagsDirs runs at all.
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [{ dir: "tags", hosts: "not-an-array" }],
        },
      }),
      "src/home.mx": "<div>home</div>",
    });

    expect(() =>
      discoverFiles(projectDir, readAngularConfig(projectDir)),
    ).toThrow(/mx\.tags\[0\]\.hosts.*must be an array of strings/);
  });
});

describe("build: byte-differ no-write", () => {
  it("does not rewrite the output file when compiled bytes are unchanged", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
    });

    build(projectDir);
    const outputPath = join(projectDir, "src/greeting.html");
    const before = readFileSync(outputPath, "utf8");

    build(projectDir);
    const after = readFileSync(outputPath, "utf8");

    expect(after).toBe(before);
  });

  it("refuses to overwrite a hand-written .html file at the page's own output path", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
      "src/greeting.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });
});

describe("checkOverwriteGuard", () => {
  it("refuses to overwrite a tagExtension output lacking the generated header", () => {
    writeProject({ "tags/card.ts": "export class Card {}\n" });
    const outputPath = join(projectDir, "tags/card.ts");

    const message = checkOverwriteGuard(outputPath);

    expect(message).toMatch(/refusing to overwrite/);
    expect(message).toContain("card.ts");
  });

  it("allows overwriting an output this tool generated", () => {
    writeProject({
      "tags/card.ts":
        "// Generated by @mxlang/angular from card.mx. Do not edit.\nexport class Card {}\n",
    });
    const outputPath = join(projectDir, "tags/card.ts");

    expect(checkOverwriteGuard(outputPath)).toBeUndefined();
  });

  it("allows writing when no output exists yet", () => {
    const outputPath = join(projectDir, "tags/new.ts");
    expect(checkOverwriteGuard(outputPath)).toBeUndefined();
  });
});

describe("security: symlinks and path escape", () => {
  it("drops tags from a symlinked tags/ directory pointing outside the project", () => {
    // @mxlang/core's discoverProjectTags walk does follow a directory
    // symlink (packages/core/src/scan.ts's walkProjectDirectories) — this
    // host's own containment check (isInside + realResolve) is what drops
    // the escape, for both the discovered template and the watched
    // directory list.
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      mkdirSync(join(outsideDir, "tags"), { recursive: true });
      writeFileSync(
        join(outsideDir, "tags/leak.mx"),
        "<span>leak</span>",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
        }),
        "src/home.mx": "<div>home</div>",
      });
      symlinkSync(join(outsideDir, "tags"), join(projectDir, "tags"), "dir");

      const { files, tagDirectories } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(files.some((f) => f.path.includes("leak.mx"))).toBe(false);
      expect(tagDirectories.some((d) => d === join(projectDir, "tags"))).toBe(
        false,
      );
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });

  it("refuses to write through a symlinked output path", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      // A generated-looking header passes checkOverwriteGuard, so the write
      // actually reaches writeIfDiffers's own symlink check — the property
      // under test.
      writeFileSync(
        join(outsideDir, "greeting.html"),
        "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->\noutside",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
        }),
        "src/greeting.mx": "<div>hi, changed</div>",
      });
      symlinkSync(
        join(outsideDir, "greeting.html"),
        join(projectDir, "src/greeting.html"),
        "file",
      );

      const result = build(projectDir);

      expect(result.ok).toBe(false);
      expect(result.errors.some((e) => /symlink/.test(e.message))).toBe(true);

      // The outside file must be untouched.
      expect(readFileSync(join(outsideDir, "greeting.html"), "utf8")).toBe(
        "<!-- Generated by @mxlang/angular from greeting.mx. Do not edit. -->\noutside",
      );
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });

  it("drops an mx.tags entry whose dir resolves outside the project", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      mkdirSync(join(outsideDir, "leaked-tags"), { recursive: true });
      writeFileSync(
        join(outsideDir, "leaked-tags/leak.mx"),
        "<span>leak</span>",
        "utf8",
      );
      writeProject({
        "package.json": JSON.stringify({
          mx: {
            host: "angular",
            angular: { include: ["src/**/*.mx"] },
            // An absolute path outside projectDir is exactly the case
            // isInside() must reject — `mx.tags[].dir` is otherwise
            // resolved verbatim, with no containment check of its own.
            tags: [{ dir: join(outsideDir, "leaked-tags") }],
          },
        }),
        "src/home.mx": "<div>home</div>",
      });

      const { files } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(files.some((f) => f.path.includes("leak.mx"))).toBe(false);
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });
});

describe("onError policy (A3's 3x2 table)", () => {
  function writeFailingProject() {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
    });
  }

  it("keep-last: cold start writes a visible error template", () => {
    writeFailingProject();
    build(projectDir);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toContain("<pre");
    expect(html).toContain("compile error");
  });

  it("keep-last: leaves a previous good output in place on a later error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/flaky.mx": "<div>good</div>",
    });
    build(projectDir);
    const goodOutput = readFileSync(join(projectDir, "src/flaky.html"), "utf8");

    writeFileSync(
      join(projectDir, "src/flaky.mx"),
      "<for from=1 to=10 step=0><div>x</div></for>",
      "utf8",
    );
    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const afterOutput = readFileSync(
      join(projectDir, "src/flaky.html"),
      "utf8",
    );
    expect(afterOutput).toBe(goodOutput);
  });

  it("error-template: overwrites even a previous good output", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "error-template" },
        },
      }),
      "src/flaky.mx": "<div>good</div>",
    });
    build(projectDir);

    writeFileSync(
      join(projectDir, "src/flaky.mx"),
      "<for from=1 to=10 step=0><div>x</div></for>",
      "utf8",
    );
    build(projectDir);

    const output = readFileSync(join(projectDir, "src/flaky.html"), "utf8");
    expect(output).toContain("compile error");
  });

  it("delete: removes any existing output and writes nothing on cold start", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "delete" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
    });
    build(projectDir);
    expect(existsSync(join(projectDir, "src/broken.html"))).toBe(false);
  });

  it("keep-last: never overwrites a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });

  it("error-template: never overwrites a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "error-template" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });

  it("delete: never deletes a hand-written file at the output path on a compile error", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"], onError: "delete" },
        },
      }),
      "src/broken.mx": "<for from=1 to=10 step=0><div>x</div></for>",
      "src/broken.html": "<div>hand-written, not ours</div>",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(
      result.errors.some((e) => /refusing to overwrite/.test(e.message)),
    ).toBe(true);
    expect(existsSync(join(projectDir, "src/broken.html"))).toBe(true);
    const html = readFileSync(join(projectDir, "src/broken.html"), "utf8");
    expect(html).toBe("<div>hand-written, not ours</div>");
  });
});

describe("mx-angular map", () => {
  /** Runs `mx-angular map <arg>`, capturing what it printed. */
  function runMapCli(arg: string): {
    exitCode: number | Promise<number>;
    logs: string[];
  } {
    const logs: string[] = [];
    const originalLog = console.log;
    console.log = (msg: string) => logs.push(msg);
    try {
      return { exitCode: runCli(["map", arg]), logs };
    } finally {
      console.log = originalLog;
    }
  }

  it("resolves an emitted position back to its line and column in the .mx", () => {
    // Multi-line on both sides: the expression is on source line 3, so a
    // resolver that ignored line structure would answer line 1 here.
    const source = "<div>\n  <p>x</p>\n  <p>${user.name}</p>\n</div>\n";
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": source,
    });
    build(projectDir);

    // Ask about the emitted `user.name`, wherever the emitter put it.
    const emitted = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    const at = emitted.indexOf("user.name");
    const before = emitted.slice(0, at);
    const line = before.split("\n").length;
    const column = at - (before.lastIndexOf("\n") + 1) + 1;

    const { exitCode, logs } = runMapCli(
      `${join(projectDir, "src/greeting.html")}:${line}:${column}`,
    );
    expect(exitCode).toBe(0);
    // Line 3, printed column 8 (offset 7): two spaces, `<p>`, `${`.
    expect(source.split("\n")[2]?.slice(7)).toBe("user.name}</p>");
    expect(logs).toEqual(["greeting.mx:3:8"]);
  });

  it("says so when the position came from no source text", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>${user.name}</div>",
    });
    build(projectDir);

    // Printed column 1 is the `<`: generated punctuation, not source text.
    const { exitCode, logs } = runMapCli(
      `${join(projectDir, "src/greeting.html")}:1:1`,
    );
    expect(exitCode).toBe(0);
    expect(logs).toEqual([
      "greeting.mx",
      "that position came from no source text (generated punctuation)",
    ]);
  });

  it("does not fabricate a position for punctuation *after* a mapped run", () => {
    // The bug this pins: a v3 segment marks where a run starts and the run
    // extends to the next segment, so without a terminator at each run's end
    // every byte after the last expression -- `</div>` here, to the end of
    // the line -- resolved to that expression's source position.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>${user.name}</div>",
    });
    build(projectDir);

    const emitted = readFileSync(join(projectDir, "src/greeting.html"), "utf8");
    // Somewhere inside the trailing `</div>`, past the end of `user.name`.
    const at = emitted.lastIndexOf("</div>") + 2;
    const before = emitted.slice(0, at);
    const line = before.split("\n").length;
    const column = at - (before.lastIndexOf("\n") + 1) + 1;

    const { exitCode, logs } = runMapCli(
      `${join(projectDir, "src/greeting.html")}:${line}:${column}`,
    );
    expect(exitCode).toBe(0);
    expect(logs).toEqual([
      "greeting.mx",
      "that position came from no source text (generated punctuation)",
    ]);
  });

  it("says so when the sidecar carries no mappings at all", () => {
    // A text-only template derives nothing from source, so its map is empty.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>hi</div>",
    });
    build(projectDir);

    const { exitCode, logs } = runMapCli(
      `${join(projectDir, "src/greeting.html")}:1:1`,
    );
    expect(exitCode).toBe(0);
    expect(logs).toEqual([
      "greeting.mx",
      "no fine-grained mapping in this sidecar (mappings empty)",
    ]);
  });

  it("rejects a 0-based column rather than reinterpreting it", () => {
    // The guard `parseMapArg` adds. Every other row in this suite was
    // re-pointed to a 1-based input, which would leave this branch
    // uncovered: delete it and the whole `mx-angular map` suite still passes.
    // A `0` column is what the sidecar uses, so accepting one silently would
    // land the reader one byte left of the position an editor shows.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/greeting.mx": "<div>\n  <p>${user.name}</p>\n</div>\n",
    });
    build(projectDir);

    const errors: string[] = [];
    const originalError = console.error;
    console.error = (msg: string) => errors.push(msg);
    try {
      expect(
        runCli(["map", `${join(projectDir, "src/greeting.html")}:2:0`]),
      ).toBe(1);
      expect(
        runCli(["map", `${join(projectDir, "src/greeting.html")}:0:1`]),
      ).toBe(1);
    } finally {
      console.error = originalError;
    }
    expect(errors).toHaveLength(2);
    for (const message of errors) {
      expect(message).toContain(
        "invalid position: line and column must be 1-based (at least 1)",
      );
    }
  });

  it("rejects a position it cannot read as numbers at all", () => {
    // `Number.isInteger`, not just `>= 1`: the `\d+` groups cannot be `NaN`
    // while the pattern holds, but `NaN < 1` is false, so a bare `< 1` check
    // would let a non-integer through if the pattern ever loosened.
    const originalError = console.error;
    const errors: string[] = [];
    console.error = (msg: string) => errors.push(msg);
    try {
      for (const arg of [
        "a.html:1:",
        "a.html:1:x",
        "a.html::1",
        "a.html:1:-2",
      ]) {
        expect(runCli(["map", arg])).toBe(1);
      }
    } finally {
      console.error = originalError;
    }
    expect(errors).toHaveLength(4);
    // Each is rejected — by the shape regex or the 1-based guard, both of
    // which exit non-zero with a message naming the position.
    expect(
      errors.every((message) => message.includes("invalid position")),
    ).toBe(true);
  });

  it("fails with a clear message when no sidecar exists", () => {
    const originalError = console.error;
    const errors: string[] = [];
    console.error = (msg: string) => errors.push(msg);
    try {
      const exitCode = runCli([
        "map",
        `${join(projectDir, "src/missing.html")}:1:1`,
      ]);
      expect(exitCode).toBe(1);
    } finally {
      console.error = originalError;
    }
    expect(errors[0]).toMatch(/could not read/);
  });
});

describe("build: .ng.mx routing", () => {
  it("compiles a .ng.mx to <basename>.ts beside it, with the header, guard and map", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        "",
        "@Component({",
        '  selector: "app-x",',
        "  template: <div>hi ${name}</div>,",
        "})",
        "export class XComponent { name = 'a'; }",
      ].join("\n"),
    });

    const result = build(projectDir);

    expect(result.errors).toEqual([]);
    // Both extension segments come off: `x.component.ts`, the name Angular
    // expects beside the source — not `x.component.ng.ts`.
    const output = join(projectDir, "src/x.component.ts");
    expect(existsSync(output)).toBe(true);
    // Never the page route's `.html`: a `.ng.mx` emits a whole module.
    expect(existsSync(join(projectDir, "src/x.component.html"))).toBe(false);

    const module = readFileSync(output, "utf8");
    expect(module).toContain(
      "// Generated by @mxlang/angular from x.component.ng.mx. Do not edit.",
    );
    expect(module).toContain("template: `<div>hi {{ name }}</div>`");
    expect(module).toContain("export class XComponent");

    const map = JSON.parse(readFileSync(`${output}.map`, "utf8"));
    expect(map.version).toBe(3);
    expect(map.sources).toEqual(["x.component.ng.mx"]);
  });

  it("refuses to overwrite a hand-written module at the output path", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-x", template: <p>hi</p> })',
        "export class XComponent {}",
      ].join("\n"),
      // A module MX did not generate: no header.
      "src/x.component.ts": "export class XComponent {}\n",
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    expect(result.errors[0]?.message).toMatch(/refusing to overwrite/);
    // The hand-written file is untouched.
    expect(readFileSync(join(projectDir, "src/x.component.ts"), "utf8")).toBe(
      "export class XComponent {}\n",
    );
  });
});

describe("build: unlocated Babel suffix (angular-build-unlocated-babel-suffix)", () => {
  it("prints a tag parse error once, at a 1-based position, with no 0-based (L:C)", () => {
    // Babel parses a tag file's top-level TypeScript; the missing type after
    // `label:` is an "Unexpected token" whose position rides in the message
    // as Babel's own 0-based `(1:32)` suffix. The tag error printer used to
    // pass non-`TranslateError` messages through verbatim, so the CLI printed
    // `Chip.mx error: Chip.mx: /abs/Chip.mx: Unexpected token (1:32)` — the
    // path twice and a 0-based column, where the README promises every
    // printed position is 1-based.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/Chip.mx":
        "export interface Input { label: }\n<div>${input.label}</div>\n",
    });
    const chip = join(projectDir, "src/tags/Chip.mx");

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const [error] = result.errors;
    expect(error?.file).toBe(chip);
    expect(error?.line).toBe(1);
    expect(error?.column).toBe(32);
    expect(error?.message).toBe("Unexpected token");

    const one = compileOne(
      { path: chip, kind: "tag" },
      readAngularConfig(projectDir),
      new Set(),
    );
    expect(one.lines[0]).toBe(`${chip}:1:33 error: Unexpected token`);
  });

  it("strips the prefix and 0-based suffix from a genuinely loc-less tag error", () => {
    // The Chip.mx error above is located (Babel attaches `loc`); this error
    // has none — a raw message carrying Babel's absolute path prefix and
    // 0-based `(L:C)` suffix. `positionOf` must strip both on the unlocated
    // branch too, and the caller prints `file: message` with no position.
    const chip = join(projectDir, "src/tags/Chip.mx");
    const at = positionOf(new Error(`${chip}: Unexpected token (1:32)`), chip);
    expect(at).toEqual({
      file: chip,
      line: undefined,
      column: undefined,
      message: "Unexpected token",
    });
  });
});

describe("build: .ng.mx round 1 review", () => {
  it("reports a .ng.mx compile error with its line and column", () => {
    // The bridge re-raises a host error as a Babel SyntaxError, not a
    // TranslateError, so testing `instanceof TranslateError` took the
    // unpositioned branch and every `.ng.mx` error printed with no position.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";', // 1
        "", // 2
        "@Component({", // 3
        '  selector: "app-x",', // 4
        "  template: <div>", // 5
        "    <try>boom</try>", // 6
        "  </div>,", // 7
        "})", // 8
        "export class XComponent {}", // 9
      ].join("\n"),
    });

    const result = build(projectDir);

    expect(result.ok).toBe(false);
    const [error] = result.errors;
    expect(error?.line).toBe(6);
    expect(error?.column).toBe(4);
    // The `(6:4)` suffix the bridge appends is stripped, so the position is
    // printed once rather than twice in two spellings.
    expect(error?.message).not.toMatch(/\(\d+:\d+\)$/);
  });

  it("discovers a .ng.mx that `include` does not match", () => {
    // A `.ng.mx` emits the component module Angular compiles, so a narrowed
    // `include` silently skipping one leaves a component that never builds.
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/pages/**/*.mx"] },
        },
      }),
      "src/pages/home.mx": "<div>home</div>",
      "src/widgets/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-x", template: <p>hi</p> })',
        "export class XComponent {}",
      ].join("\n"),
    });

    const result = build(projectDir);

    expect(result.errors).toEqual([]);
    expect(existsSync(join(projectDir, "src/widgets/x.component.ts"))).toBe(
      true,
    );
  });
});

describe("build: .ng.mx round 2 review", () => {
  it("shifts the .map by the generated header, so positions are not off by one", () => {
    // The map is generated over the module alone, then the header is
    // prepended to the file — so without a shift every generated line the
    // map describes sits one line higher than where it actually is, and
    // `mx-angular map` is wrong for every `.ng.mx`.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        "",
        "@Component({",
        '  selector: "app-x",',
        "  template: <div>",
        "    <p>${first}</p>",
        "    <p>${second}</p>",
        "  </div>,",
        "})",
        "export class XComponent { first = 1; second = 2; }",
      ].join("\n"),
    });

    expect(build(projectDir).errors).toEqual([]);

    const output = join(projectDir, "src/x.component.ts");
    const emitted = readFileSync(output, "utf8").split("\n");
    const map = JSON.parse(readFileSync(`${output}.map`, "utf8"));

    // One `;` per header line, so mapping line N describes emitted line N.
    const headerLines = emitted.filter((l) =>
      l.startsWith("// Generated by @mxlang/angular"),
    ).length;
    expect(headerLines).toBeGreaterThan(0);
    expect(map.mappings.startsWith(";".repeat(headerLines))).toBe(true);

    // The header's own lines map to nothing, which is the point.
    const lines = map.mappings.split(";");
    for (let i = 0; i < headerLines; i++) expect(lines[i]).toBe("");
  });

  it("surfaces the literal-Angular-syntax warning from build() with its position", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-x", template: <div>',
        "  @if (title) {",
        "    <p>x</p>",
        "  }",
        "</div> })",
        "export class XComponent { title = 'hi'; }",
      ].join("\n"),
      "src/page.mx": "<p>{{ name }}</p>",
    });

    const result = build(projectDir);
    const literal = result.warnings.filter((w) =>
      /literal text in an MX template/.test(w.message),
    );

    expect(result.ok).toBe(true);
    expect(
      literal
        .map((w) => [basename(w.file ?? ""), w.line, w.column])
        .sort((a, b) => String(a[0]).localeCompare(String(b[0]))),
    ).toEqual([
      ["page.mx", 1, 3],
      ["x.component.ng.mx", 3, 2],
    ]);
  });

  it("build() keeps the literal-syntax scan inside a concise text node", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/leak.mx": 'div\n  -- me@x\n  span title="{{ q }}" -- ok\n',
      "src/two.mx": "div\n  -- {{ a }}\n  p -- {{ b }}\n",
    });

    const result = build(projectDir);
    const literal = result.warnings.filter((w) =>
      /literal text in an MX template/.test(w.message),
    );

    expect(
      literal
        .map((w) => [basename(w.file ?? ""), w.line, w.column])
        .sort(
          (a, b) =>
            String(a[1]).localeCompare(String(b[1])) ||
            Number(a[2]) - Number(b[2]),
        ),
    ).toEqual([
      ["two.mx", 2, 5],
      ["two.mx", 3, 7],
    ]);
  });

  it("build() stays silent inside an html-script body", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/page.mx":
        '<p>x</p>\n<html-script>var t = "{{ y }}";</html-script>\n',
    });

    const result = build(projectDir);

    expect(
      result.warnings.filter((w) =>
        /literal text in an MX template/.test(w.message),
      ),
    ).toEqual([]);
  });

  it("rejects a .ng.mx inside a tags/ directory", () => {
    // Routed as a tag it reached the tag compiler and failed with a nonsense
    // error about its `@Component` decorator instead of saying what is wrong.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/bad.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-bad", template: <p>x</p> })',
        "export class BadComponent {}",
      ].join("\n"),
    });

    const result = build(projectDir);

    expect(
      result.warnings.some((w) =>
        /a `\.ng\.mx` file is a component module, not a tag/.test(w.message),
      ),
    ).toBe(true);
    // And no tag module written beside it.
    expect(existsSync(join(projectDir, "src/tags/bad.component.ts"))).toBe(
      false,
    );
  });

  it("diagnoses a .ng.mx under tags/ without dropping other tags directories", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          angular: { include: ["src/**/*.mx"] },
          tags: [{ dir: "src/tags" }, { dir: "src/other-tags" }],
        },
      }),
      "src/page.mx": "<div><good/><fine/></div>",
      "src/tags/bad.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-bad", template: <p>x</p> })',
        "export class BadComponent {}",
      ].join("\n"),
      "src/tags/good.mx": "<p>good</p>",
      "src/other-tags/fine.mx": "<p>fine</p>",
    });

    const result = build(projectDir);

    expect(
      result.warnings.some((w) =>
        /a `\.ng\.mx` file is a component module, not a tag/.test(w.message),
      ),
    ).toBe(true);

    expect(existsSync(join(projectDir, "src/tags/bad.component.ts"))).toBe(
      false,
    );
    expect(existsSync(join(projectDir, "src/tags/good.ts"))).toBe(true);
    expect(existsSync(join(projectDir, "src/other-tags/fine.ts"))).toBe(true);
  });

  it("treats a .solid.mx under tags/ as a rejection, never as .ng.mx", () => {
    // `build()` is a direct entry, so it resolves its targets from this
    // package's own descriptor unless the caller passes a lookup of its own
    // (design note §5.1, rule (c)). `solid` is therefore not a file kind it
    // knows, and decision 137's second branch reports it: the file cannot be
    // called as a tag. What must not happen either way is the `.ng.mx`
    // wording, which would tell the author the wrong thing about a file this
    // host does not own.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/widget.solid.mx": [
        'const Widget = () => <div class="widget">hi</div>;',
        "export default Widget;",
      ].join("\n"),
    });

    // A caller holding the built-in lookup gets core's host-module rejection:
    // the file is skipped, warned about in core's own words, and nothing is
    // written beside it.
    const built = build(
      projectDir,
      testTargetLookupWithSegments("ng", "solid"),
    );

    expect(built.errors).toEqual([]);
    expect(
      built.warnings.some((w) =>
        /is a host module file, not a tag template/.test(w.message),
      ),
    ).toBe(true);
    expect(
      built.warnings.some((w) =>
        /a `\.ng\.mx` file is a component module, not a tag/.test(w.message),
      ),
    ).toBe(false);
    // And nothing is compiled beside it.
    expect(existsSync(join(projectDir, "src/tags/widget.ts"))).toBe(false);
    expect(existsSync(join(projectDir, "src/tags/widget.html"))).toBe(false);
  });
});

describe("discovery: core's host-module extension rule", () => {
  it("routes a `.ng.mx` file to the ng.mx module compiler", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-x", template: <p>hi</p> })',
        "export class XComponent {}",
      ].join("\n"),
    });

    const result = discoverFiles(projectDir, readAngularConfig(projectDir));

    const routed = result.files.find((f) => f.path.endsWith(".ng.mx"));
    expect(routed?.kind).toBe("ngmx");
  });

  it("excludes another host's file kind from page compilation when the caller passes its lookup", () => {
    // `discoverFiles` takes the registered targets to route by. With the
    // built-in lookup (what the oracle and a tool with the registry in hand
    // pass) `solid` is a known file kind and the file is excluded with core's
    // host-module diagnostic. With this package's own descriptor it is not a
    // kind it knows — see the next test.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.solid.mx": "const x = () => <p>hi</p>;",
    });

    const result = discoverFiles(
      projectDir,
      readAngularConfig(projectDir),
      testTargetLookupWithSegments("ng", "solid"),
    );

    expect(result.files.some((f) => f.path.endsWith(".solid.mx"))).toBe(false);
    expect(
      result.diagnostics.some((d) =>
        /`x\.solid\.mx` is a host module file, not a tag template/.test(
          d.message,
        ),
      ),
    ).toBe(true);
  });

  it("compiles a foreign file kind as a page when it knows only its own targets", () => {
    // The other half of the same fact: `discoverFiles` decides by the lookup it
    // is given, and this package's own descriptor knows only `ng`. A caller
    // that wants foreign kinds routed must pass a lookup that holds them.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/x.solid.mx": "const x = () => <p>hi</p>;",
    });

    const result = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(result.files.some((f) => f.path.endsWith(".solid.mx"))).toBe(true);
  });

  it("reports a positioned diagnostic for a `.ng.mx` under tags/ and never routes it", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/bad.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-bad", template: <p>x</p> })',
        "export class BadComponent {}",
      ].join("\n"),
    });

    const result = discoverFiles(projectDir, readAngularConfig(projectDir));

    expect(result.files.some((f) => f.path.endsWith(".ng.mx"))).toBe(false);
    const diagnostics = result.diagnostics.filter((d) =>
      d.file.endsWith("bad.component.ng.mx"),
    );
    // Exactly one: the guard's duplicate blocks are gone.
    expect(diagnostics).toHaveLength(1);
    expect(diagnostics[0]?.message).toMatch(/component module, not a tag/);
  });

  it("keeps core's own message for a `.solid.mx` under tags/ when the lookup knows it", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/**/*.mx"] } },
      }),
      "src/tags/bad.solid.mx": "const x = () => <p>x</p>;",
    });

    const result = discoverFiles(
      projectDir,
      readAngularConfig(projectDir),
      testTargetLookupWithSegments("ng", "solid"),
    );

    expect(result.files.some((f) => f.path.endsWith(".solid.mx"))).toBe(false);
    expect(
      result.diagnostics.filter((d) =>
        /`bad\.solid\.mx` is a host module file, not a tag template; tag templates are `\.mx`/.test(
          d.message,
        ),
      ),
    ).toHaveLength(1);
  });

  it("positions every host-module diagnostic at line 1, column 0", () => {
    // Core's `rejectHostModuleFile` positions its diagnostic at the file
    // (line 1, column 0); the include path must match, and neither path may
    // drop the position on the way to the build's warnings.
    writeProject({
      "package.json": JSON.stringify({
        mx: { host: "angular", angular: { include: ["src/pages/**/*.mx"] } },
      }),
      "src/pages/via-include.solid.mx": "const x = () => <p>x</p>;",
      "src/tags/via-tags.solid.mx": "const x = () => <p>x</p>;",
      "src/tags/via-tags.component.ng.mx": [
        'import { Component } from "@angular/core";',
        '@Component({ selector: "app-t", template: <p>x</p> })',
        "export class TComponent {}",
      ].join("\n"),
    });

    const { diagnostics } = discoverFiles(
      projectDir,
      readAngularConfig(projectDir),
      testTargetLookupWithSegments("ng", "solid"),
    );

    for (const name of [
      "via-include.solid.mx",
      "via-tags.solid.mx",
      "via-tags.component.ng.mx",
    ]) {
      const found = diagnostics.filter((d) => d.file.endsWith(name));
      expect(found, name).toHaveLength(1);
      expect(found[0]?.line, name).toBe(1);
      expect(found[0]?.column, name).toBe(0);
    }
  });

  it("reports no diagnostic for a host-module file an include glob reaches outside the project", () => {
    const outsideDir = mkdtempSync(join(tmpdir(), "mx-angular-outside-"));
    try {
      writeFileSync(join(outsideDir, "leak.solid.mx"), "const x = 1;", "utf8");
      writeProject({
        "package.json": JSON.stringify({
          mx: { host: "angular", angular: { include: ["linked/**/*.mx"] } },
        }),
      });
      symlinkSync(outsideDir, join(projectDir, "linked"), "dir");

      const { files, diagnostics } = discoverFiles(
        projectDir,
        readAngularConfig(projectDir),
      );

      expect(files).toHaveLength(0);
      expect(diagnostics).toHaveLength(0);
    } finally {
      rmSync(outsideDir, { recursive: true, force: true });
    }
  });
});

describe("build: the package's defaultTag (decision 145)", () => {
  const manifest = (value: unknown) =>
    JSON.stringify({
      mx: {
        host: "angular",
        angular: { include: ["src/**/*.mx"] },
        "angular-template": { defaultTag: value },
      },
    });

  it("a page compiles the unnamed tag to the configured tag", () => {
    writeProject({
      "package.json": manifest("section"),
      "src/page.mx": "<.x>hi</>",
    });
    const result = build(projectDir);
    expect(result.ok).toBe(true);
    expect(readFileSync(join(projectDir, "src/page.html"), "utf8")).toContain(
      '<section class="x">hi</section>',
    );
  });

  it("an invalid value falls back to the built-in and warns once at the package.json value", () => {
    writeProject({
      "package.json": manifest("input"),
      "src/a.mx": "<.x>hi</>",
      "src/b.mx": "<.y>hi</>",
    });
    const result = build(projectDir);
    expect(result.ok).toBe(true);
    expect(readFileSync(join(projectDir, "src/a.html"), "utf8")).toContain(
      '<div class="x">hi</div>',
    );
    const own = result.warnings.filter((w) =>
      w.message.includes("invalid `defaultTag` value"),
    );
    expect(own).toHaveLength(1);
    expect(own[0]?.message).toContain(
      "`<input>` is a void tag, not a plain tag",
    );
    expect(own[0]).toMatchObject({
      file: join(projectDir, "package.json"),
      line: 1,
    });
  });
});

describe("build: a contract's invalid defaultTag (decision 145, review round 2)", () => {
  it("is the one declaration error, through the build's warnings, once for many files", () => {
    writeProject({
      "package.json": JSON.stringify({
        mx: {
          host: "angular",
          contracts: "./contracts.ts",
          angular: { include: ["src/**/*.mx"] },
        },
      }),
      "contracts.ts": 'export default { "my-list": { defaultTag: "nope" } };\n',
      "src/a.mx": "<div>a</div>",
      "src/b.mx": "<div>b</div>",
    });
    const result = build(projectDir);
    const own = result.warnings.filter((w) =>
      w.message.includes("invalid `defaultTag` value"),
    );
    expect(own).toHaveLength(1);
    expect(own[0]?.file).toBe(join(realpathSync(projectDir), "contracts.ts"));
  });
});
